/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Connection.ConnectionFactory;
import auth.ClientAuth;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import table.Client;
import table.Exam;
import table.Scheduling;

/**
 *
 * @author gscoe
 */
public final class ClientScreen extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    private String CPF_C;

    public String getCPF_C() {
        return CPF_C;
    }

    public void setCPF_C(String CPF_C) {
        this.CPF_C = CPF_C;
    }
    
    
    public ClientScreen() {
        initComponents();
        setLocationRelativeTo(null);
        hiddenElements();
        getCpfTest();
    }
    
     public void getCpfTest(){
         //Client cl = new Client();
         
         System.out.println(getCPF_C());
     }
     
     public void hiddenElements(){
        
        name.setVisible(false);
        telefone.setVisible(false);
        Cep.setVisible(false);
        labelExam.setVisible(false);
        inputCpfExam.setVisible(false);
        inputDataExam.setVisible(false);
        inputIdExam.setVisible(false);
        inputNameExam.setVisible(false);
        TableList.setVisible(false);
        BtnListExam.setVisible(false);
        btnAddExam.setVisible(false);
        btnAlterDataClient.setVisible(false);
        btnBack.setVisible(false);
    }
    
    public void showElements(){
        name.setVisible(true);
        telefone.setVisible(true);
        Cep.setVisible(true);
        labelExam.setVisible(true);
        inputCpfExam.setVisible(true);
        inputDataExam.setVisible(true);
        inputIdExam.setVisible(true);
        inputNameExam.setVisible(true);
        TableList.setVisible(true);
        BtnListExam.setVisible(true);
        btnAddExam.setVisible(true);
        btnAlterDataClient.setVisible(true);
        btnBack.setVisible(true);  
        btnSearch.setVisible(false);
        inputSearch.setVisible(false);
        labelCpfSearch.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelName = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAlterDataClient = new javax.swing.JButton();
        labelExam = new javax.swing.JLabel();
        inputCpfExam = new javax.swing.JTextField();
        inputIdExam = new javax.swing.JTextField();
        inputNameExam = new javax.swing.JTextField();
        inputDataExam = new javax.swing.JTextField();
        btnAddExam = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        BtnListExam = new javax.swing.JButton();
        inputSearch = new javax.swing.JTextField();
        labelCpfSearch = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        Cep = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jDesktopPane2.setLayer(jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane3)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane3)
                .addContainerGap())
        );

        labelName.setBackground(new java.awt.Color(51, 51, 51));
        labelName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Clínica BioTech");

        btnAlterDataClient.setBackground(new java.awt.Color(0, 204, 255));
        btnAlterDataClient.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAlterDataClient.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterDataClient.setText("Alterar dados");
        btnAlterDataClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterDataClientActionPerformed(evt);
            }
        });

        labelExam.setBackground(new java.awt.Color(51, 51, 51));
        labelExam.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        labelExam.setForeground(new java.awt.Color(255, 255, 255));
        labelExam.setText("Adicionar Exame");

        inputCpfExam.setBackground(new java.awt.Color(51, 51, 51));
        inputCpfExam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inputCpfExam.setForeground(new java.awt.Color(255, 255, 255));
        inputCpfExam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Cpf:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        inputCpfExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCpfExamActionPerformed(evt);
            }
        });

        inputIdExam.setBackground(new java.awt.Color(51, 51, 51));
        inputIdExam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inputIdExam.setForeground(new java.awt.Color(255, 255, 255));
        inputIdExam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Chave de acesso:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        inputIdExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdExamActionPerformed(evt);
            }
        });

        inputNameExam.setBackground(new java.awt.Color(51, 51, 51));
        inputNameExam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inputNameExam.setForeground(new java.awt.Color(255, 255, 255));
        inputNameExam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Tipo de exame:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        inputDataExam.setBackground(new java.awt.Color(51, 51, 51));
        inputDataExam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inputDataExam.setForeground(new java.awt.Color(255, 255, 255));
        inputDataExam.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Data:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        inputDataExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDataExamActionPerformed(evt);
            }
        });

        btnAddExam.setBackground(new java.awt.Color(102, 255, 102));
        btnAddExam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAddExam.setForeground(new java.awt.Color(255, 255, 255));
        btnAddExam.setText("Adicionar");
        btnAddExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExamActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnBack.setText("Voltar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        BtnListExam.setBackground(new java.awt.Color(0, 255, 204));
        BtnListExam.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        BtnListExam.setForeground(new java.awt.Color(255, 255, 255));
        BtnListExam.setText("Listar Exames");
        BtnListExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListExamActionPerformed(evt);
            }
        });

        inputSearch.setBackground(new java.awt.Color(51, 51, 51));
        inputSearch.setForeground(new java.awt.Color(255, 255, 255));
        inputSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Cpf:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        inputSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSearchActionPerformed(evt);
            }
        });

        labelCpfSearch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelCpfSearch.setForeground(new java.awt.Color(255, 255, 255));
        labelCpfSearch.setText("Digite seu cpf novamente para continuar");

        btnSearch.setBackground(new java.awt.Color(255, 102, 102));
        btnSearch.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Continuar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        name.setBackground(new java.awt.Color(51, 51, 51));
        name.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("jLabel3");

        telefone.setBackground(new java.awt.Color(51, 51, 51));
        telefone.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        telefone.setForeground(new java.awt.Color(255, 255, 255));
        telefone.setText("jLabel3");

        Cep.setBackground(new java.awt.Color(51, 51, 51));
        Cep.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        Cep.setForeground(new java.awt.Color(255, 255, 255));
        Cep.setText("jLabel3");

        TableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cpf", "Nome", "Data", "Chave:", "Resultado"
            }
        ));
        jScrollPane1.setViewportView(TableList);

        javax.swing.GroupLayout labelNameLayout = new javax.swing.GroupLayout(labelName);
        labelName.setLayout(labelNameLayout);
        labelNameLayout.setHorizontalGroup(
            labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelNameLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(labelNameLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(labelNameLayout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddExam, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(labelNameLayout.createSequentialGroup()
                        .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputCpfExam, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDataExam, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 53, Short.MAX_VALUE)
                        .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNameExam, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputIdExam, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(labelNameLayout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCpfSearch)
                                .addGroup(labelNameLayout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(inputSearch)
                                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)))))
                        .addComponent(labelExam))
                    .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(labelNameLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jLabel2))
                        .addComponent(telefone)
                        .addComponent(name)
                        .addGroup(labelNameLayout.createSequentialGroup()
                            .addComponent(Cep)
                            .addGap(243, 243, 243)
                            .addComponent(btnAlterDataClient, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnListExam, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1382, 1382, 1382))
        );
        labelNameLayout.setVerticalGroup(
            labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelNameLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(labelNameLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(telefone)
                        .addGap(11, 11, 11))
                    .addGroup(labelNameLayout.createSequentialGroup()
                        .addComponent(name)
                        .addGap(44, 44, 44)))
                .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cep)
                    .addComponent(btnAlterDataClient, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnListExam, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(labelNameLayout.createSequentialGroup()
                        .addComponent(labelCpfSearch)
                        .addGap(18, 18, 18)
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelExam)
                        .addGap(18, 18, 18)
                        .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputCpfExam, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputIdExam, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNameExam, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDataExam, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(labelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddExam, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(labelName);

        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2)
                .addGap(622, 622, 622))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Client cl = new Client();
        cl.setCPF_C(inputSearch.getText());

        try {
            cl.checkClient();
        } catch (SQLException ex) {
            Logger.getLogger(ClientScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

        name.setText("Nome: "+ cl.getNAME_C());
        telefone.setText("CEP: " + cl.getCEP_C());
        Cep.setText("Celular: " + cl.getPHONE_C());

        showElements();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void inputSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSearchActionPerformed

    private void BtnListExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListExamActionPerformed
        // TODO add your handling code here:
        
        Exam ex = new Exam();
                
        DefaultTableModel dtmPacientes = (DefaultTableModel) TableList.getModel();
        dtmPacientes.setRowCount(0);

        String sql = "SELECT * FROM tb_exam WHERE CPF_E=?";
        
        ConnectionFactory factory = new ConnectionFactory();
        try (Connection c = factory.obtemConexao()){
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setString(1, inputSearch.getText());
            ps.execute();
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                ex.setCPF_E(rs.getString("CPF_E"));
                ex.setNAME_E(rs.getString("NAME_E"));
                ex.setDATE_E(rs.getString("DATE_E"));
                ex.setID_E(rs.getString("ID_E"));
                ex.setRESULT_E(rs.getString("RESULT_E"));
                
      
                Object[] data = {ex.getCPF_E(), ex.getNAME_E(), ex.getDATE_E(), ex.getID_E(), ex.getRESULT_E()}; 
                dtmPacientes.addRow(data);       
            }
        } catch (Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_BtnListExamActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ClientLogin().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExamActionPerformed

        String inputCpf = inputCpfExam.getText();
        String inputDate = inputDataExam.getText();
        String inputId = inputIdExam.getText();
        String inputName = inputNameExam.getText();

        Scheduling sh = new Scheduling();

        sh.setCPF_SH(inputCpf);
        sh.setDATE_SH(inputDate);
        sh.setID_SH(inputId);
        sh.setNAME_SH(inputName);

        try {
            sh.addsh();
        } catch (SQLException ex) {
            Logger.getLogger(ClientScreen.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null," erro ao cadastrar Exame, revisite os dados digitados");
        }
        JOptionPane.showMessageDialog(null, "Exame cadastrado com sucesso");

    }//GEN-LAST:event_btnAddExamActionPerformed

    private void inputDataExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDataExamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDataExamActionPerformed

    private void inputCpfExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCpfExamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCpfExamActionPerformed

    private void btnAlterDataClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterDataClientActionPerformed
        this.dispose(); // fechar tela atual
        new ChangeDataClient().setVisible(true); // abre a classe que você selecionou
    }//GEN-LAST:event_btnAlterDataClientActionPerformed

    private void inputIdExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdExamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdExamActionPerformed
    
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientScreen().setVisible(true);
                
            }
            
        });
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnListExam;
    private javax.swing.JLabel Cep;
    private javax.swing.JTable TableList;
    private javax.swing.JButton btnAddExam;
    private javax.swing.JButton btnAlterDataClient;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField inputCpfExam;
    private javax.swing.JTextField inputDataExam;
    private javax.swing.JTextField inputIdExam;
    private javax.swing.JTextField inputNameExam;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCpfSearch;
    private javax.swing.JLabel labelExam;
    private javax.swing.JPanel labelName;
    private javax.swing.JLabel name;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
